FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt upgrade -y && \
    apt install software-properties-common -y && \
    add-apt-repository universe && \
    apt update && apt install curl -y

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update && apt upgrade
RUN apt install ros-foxy-desktop python3-argcomplete -y
RUN apt install ros-foxy-ros-base python3-argcomplete -y
RUN apt install ros-dev-tools -y
RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc

# 2章 install packages
RUN apt install python3-argcomplete -y
RUN apt install python3-colcon-common-extensions
RUN apt install x11-apps